In [ ]:
import torch

In [ ]:
basic_tensor_one = torch.tensor([1,2,3])
basic_tensor_two = torch.tensor([4,5,6])

$
\text{complex_tensor_one} = \begin{pmatrix}
    \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{pmatrix}, &
    \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{pmatrix}, &
    \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{pmatrix}
\end{pmatrix}
$


$
\text{complex_tensor_two} = \begin{pmatrix}
    \begin{pmatrix} 10 & 20 & 30 \\ 40 & 50 & 60 \end{pmatrix}, &
    \begin{pmatrix} 10 & 20 & 30 \\ 40 & 50 & 60 \end{pmatrix}, &
    \begin{pmatrix} 10 & 20 & 30 \\ 40 & 50 & 60 \end{pmatrix}
\end{pmatrix}
$

In [ ]:
complex_tensor_one = torch.tensor([[
    [1,2,3],
    [4,5,6]
],
[
    [1,2,3],
    [4,5,6]
],
[
    [1,2,3],
    [4,5,6]
]])


complex_tensor_two = torch.tensor([[
    [10,20,30],
    [40,50,60]
],
[
    [10,20,30],
    [40,50,60]
],
[
    [10,20,30],
    [40,50,60]
]])

In [ ]:
complex_tensor_two.shape

torch.Size([3, 2, 3])

In [ ]:
small_tensor = torch.tensor([100, 1])

# Addition of Two Tensors

In [ ]:
basic_result = torch.add(basic_tensor_one, basic_tensor_two)

In [ ]:
basic_result

tensor([5, 7, 9])

In [ ]:
complex_result = torch.add(complex_tensor_one, complex_tensor_two)

In [ ]:
complex_result

tensor([[[11, 22, 33],
         [44, 55, 66]],

        [[11, 22, 33],
         [44, 55, 66]],

        [[11, 22, 33],
         [44, 55, 66]]])

In [ ]:
_result = torch.add(complex_result, basic_tensor_one)

In [ ]:
_result

tensor([[[12, 24, 36],
         [45, 57, 69]],

        [[12, 24, 36],
         [45, 57, 69]],

        [[12, 24, 36],
         [45, 57, 69]]])

In [ ]:
'''This cell should throw an error'''
# small_plus_complex =torch.add(complex_result, small_tensor)

In [ ]:
# small_plus_complex

# Subtraction

Works pretty much the same way as addition

In [ ]:
basic_sub = torch.subtract(basic_tensor_one, basic_tensor_two)

In [ ]:
basic_sub

tensor([-3, -3, -3])

In [ ]:
complex_sub = torch.subtract(complex_tensor_one, complex_tensor_two)

In [ ]:
complex_sub

tensor([[[ -9, -18, -27],
         [-36, -45, -54]],

        [[ -9, -18, -27],
         [-36, -45, -54]],

        [[ -9, -18, -27],
         [-36, -45, -54]]])

In [ ]:
basic_complex_sub = torch.subtract(complex_result, basic_tensor_one)

In [ ]:
basic_complex_sub

tensor([[[10, 20, 30],
         [43, 53, 63]],

        [[10, 20, 30],
         [43, 53, 63]],

        [[10, 20, 30],
         [43, 53, 63]]])

# Multiplication


This is element wise multiplication, for matrix multiplication, see matmul

In [ ]:
torch.mul(basic_tensor_one, 6)

tensor([ 6, 12, 18])

In [ ]:
torch.mul(complex_tensor_one, 9)

tensor([[[ 9, 18, 27],
         [36, 45, 54]],

        [[ 9, 18, 27],
         [36, 45, 54]],

        [[ 9, 18, 27],
         [36, 45, 54]]])

In [ ]:
torch.mul(complex_tensor_one, basic_tensor_one)

tensor([[[ 1,  4,  9],
         [ 4, 10, 18]],

        [[ 1,  4,  9],
         [ 4, 10, 18]],

        [[ 1,  4,  9],
         [ 4, 10, 18]]])

In [ ]:
torch.mul(complex_tensor_one, complex_tensor_two)

tensor([[[ 10,  40,  90],
         [160, 250, 360]],

        [[ 10,  40,  90],
         [160, 250, 360]],

        [[ 10,  40,  90],
         [160, 250, 360]]])

# Division

This performs element wise division

In [ ]:
torch.div(basic_tensor_one, 6)

tensor([0.1667, 0.3333, 0.5000])

In [ ]:
torch.div(complex_tensor_one, 9)

tensor([[[0.1111, 0.2222, 0.3333],
         [0.4444, 0.5556, 0.6667]],

        [[0.1111, 0.2222, 0.3333],
         [0.4444, 0.5556, 0.6667]],

        [[0.1111, 0.2222, 0.3333],
         [0.4444, 0.5556, 0.6667]]])

In [ ]:
torch.div(complex_tensor_one, basic_tensor_one)

tensor([[[1.0000, 1.0000, 1.0000],
         [4.0000, 2.5000, 2.0000]],

        [[1.0000, 1.0000, 1.0000],
         [4.0000, 2.5000, 2.0000]],

        [[1.0000, 1.0000, 1.0000],
         [4.0000, 2.5000, 2.0000]]])

In [ ]:
torch.div(complex_tensor_one, complex_tensor_two)

tensor([[[0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000]],

        [[0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000]],

        [[0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000]]])

# Matrix Multiplication

In [ ]:
torch.matmul(basic_tensor_one, basic_tensor_two)

tensor(32)

In [ ]:
torch.matmul(complex_tensor_one, basic_tensor_one)

tensor([[14, 32],
        [14, 32],
        [14, 32]])

In [ ]:
torch.matmul(complex_tensor_one, basic_tensor_two)

tensor([[32, 77],
        [32, 77],
        [32, 77]])

In [ ]:
# This should throw an error
# torch.matmul(complex_tensor_one, complex_tensor_two)

RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [3, 3] but got: [3, 2].

$\begin{bmatrix}
        0 & 0 \\
        0 & 0 \\
        0 & 0
    \end{bmatrix} \\[1em]
    \begin{bmatrix}
        0 & 0 \\
        0 & 0 \\
        0 & 0
    \end{bmatrix} \\[1em]
    \begin{bmatrix}
        0 & 0 \\
        0 & 0 \\
        0 & 0
    \end{bmatrix}
$




In [ ]:
fixed_tensor = torch.zeros([3,3,2], dtype = int)

In [ ]:
matmul_res = torch.matmul(complex_tensor_one, fixed_tensor)

In [ ]:
matmul_res

tensor([[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]])

In [ ]:
matmul_res.shape

torch.Size([3, 2, 2])