In [ ]:
import torch

# Creating a Tensor

A tensor can be created using torch.tensor method

In [ ]:
scalar = torch.tensor(7)

In [ ]:
vector = torch.tensor([1,2,3])

In [ ]:
MATRIX = torch.tensor([[1,2,3], [1,2,3]])

In [ ]:
TENSOR = torch.tensor(
    [[
      [
          [
              [1,2], [1,3]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ]
      ],
      [
          [
              [1,2], [1,3]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ]
      ],
      [
          [
              [1,2], [1,3]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ]
      ],
      [
          [
              [1,2], [1,3]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ]
      ],
      [
          [
              [1,2], [1,3]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ]
      ]
    ],
     [
      [
          [
              [1,2], [1,3]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ]
      ],
      [
          [
              [1,2], [1,3]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ]
      ],
      [
          [
              [1,2], [1,3]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ]
      ],
      [
          [
              [1,2], [1,3]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ]
      ],
      [
          [
              [1,2], [1,3]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ],
          [
              [1,2], [1,2]
          ]
      ]
    ]
    ]
)

# Dimesnions of a Tensor

The ndim method tells us the dimensions of a Tensor.

Here is some common terminology that is used to refer to tensors based on their dimensions:



*   <b>0 dimensions</b> : Scalar
*   <b>1 dimensions</b> : Vector
*   <b>2 dimensions</b> : Matrix
*   <b>3+ dimensions</b> : Tensor

One way to think about the dimensions of a Tensor is to check the number of nested brackets.

In the case of scalars, there is no square brackets so the dimension is 0.


In the case of tensors (in the above example) there are 3 nested square brackets so the dimension is 3.

You can see the above logic applies to matrices and vectors too,



In [ ]:
print(scalar.ndim)

0


In [ ]:
print(vector.ndim)

1


In [ ]:
print(MATRIX.ndim)

2


In [ ]:
print(TENSOR.ndim)

5


# Shape of a tensor
The shape of a tensor tells you how many elements are there along each dimension.

Note that the shape of a tensor will always return an output that is the of the same length as the dimensions of that tensor



In [ ]:
print(scalar.shape)

torch.Size([])


In [ ]:
print(vector.shape)

torch.Size([3])


In [ ]:
print(MATRIX.shape)

torch.Size([2, 3])


In [ ]:
print(TENSOR.shape)

torch.Size([2, 5, 5, 2, 2])


# Random Tensors
Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1)

In [ ]:
random_vector = torch.rand([3])
print(random_vector)
print(f"the shape of my random scalar is {random_vector.shape}")
print(f"the dimensions of my random scalar is {random_vector.ndim}")

tensor([0.3666, 0.5214, 0.8358])
the shape of my random scalar is torch.Size([3])
the dimensions of my random scalar is 1


In [ ]:
random_matrix = torch.rand([3,3])
print(random_matrix)
print(f"the shape of my random scalar is {random_matrix.shape}")
print(f"the dimensions of my random scalar is {random_matrix.ndim}")

tensor([[0.8492, 0.7647, 0.8005],
        [0.5238, 0.9133, 0.4959],
        [0.2638, 0.2642, 0.0919]])
the shape of my random scalar is torch.Size([3, 3])
the dimensions of my random scalar is 2


In [ ]:
random_tensor = torch.rand([5,3,2])
print(random_tensor)
print(f"the shape of my random scalar is {random_tensor.shape}")
print(f"the dimensions of my random scalar is {random_tensor.ndim}")

tensor([[[0.2109, 0.0336],
         [0.5108, 0.6742],
         [0.1961, 0.5930]],

        [[0.6128, 0.6335],
         [0.2947, 0.4385],
         [0.2329, 0.4607]],

        [[0.1992, 0.4911],
         [0.8062, 0.3810],
         [0.4103, 0.3434]],

        [[0.0332, 0.1769],
         [0.1099, 0.2844],
         [0.6556, 0.2280]],

        [[0.5469, 0.1100],
         [0.1410, 0.7520],
         [0.8156, 0.2823]]])
the shape of my random scalar is torch.Size([5, 3, 2])
the dimensions of my random scalar is 3


# ZEROS
Returns a tensor filled with the scalar value 0, with the shape defined by the variable argument size.

In [82]:
zeros_tensor = torch.zeros([5,3,2])
print(zeros_tensor)
print(f"the shape of my random scalar is {zeros_tensor.shape}")
print(f"the dimensions of my random scalar is {zeros_tensor.ndim}")

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])
the shape of my random scalar is torch.Size([5, 3, 2])
the dimensions of my random scalar is 3


Now say you didn't want to pass in the shape of the tensor manually, youc could pass in another tensor and pytorch will get the shape of that tensor and generate a new tensor for you.

To do this we must use the zeros like function.

In [81]:
zeros_like_tensor = torch.zeros_like(TENSOR)
print(zeros_like_tensor)
print(f"the shape of my random scalar is {zeros_like_tensor.shape}")
print(f"the dimensions of my random scalar is {zeros_like_tensor.ndim}")

tensor([[[[[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]]],


         [[[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]]],


         [[[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]]],


         [[[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]]],


         [[[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0

# ONES
Works the same way as Zero does, but instead of filling it with zeros we get it filled with ones

In [ ]:
ones_tensor = torch.zeros([5,3,2])
print(ones_tensor)
print(f"the shape of my random scalar is {ones_tensor.shape}")
print(f"the dimensions of my random scalar is {ones_tensor.ndim}")

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])
the shape of my random scalar is torch.Size([5, 3, 2])
the dimensions of my random scalar is 3


Similar to the zeros like function, we have a ones_like method that does the same thing but populates the tensor with 1's.

In [83]:
ones_like_tensor = torch.zeros_like(TENSOR)
print(ones_like_tensor)
print(f"the shape of my random scalar is {ones_like_tensor.shape}")
print(f"the dimensions of my random scalar is {ones_like_tensor.ndim}")

tensor([[[[[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]]],


         [[[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]]],


         [[[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]]],


         [[[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]]],


         [[[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0, 0]],

          [[0, 0],
           [0